# Generated by Django 4.0.4 on 2022-06-06 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0002_alter_likes_options_alter_follow_follower_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likes',
            name='liked_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instagram.profile'),
        ),
    ]
