# Generated by Django 4.0.4 on 2022-06-06 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0006_alter_profile_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subscriber',
        ),
    ]
