# Generated by Django 4.0.4 on 2022-06-07 12:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('instagram', '0010_alter_image_comment_alter_image_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='comment',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='image',
            name='like',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='image_likes', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
