# Generated by Django 4.0.4 on 2022-06-07 12:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('instagram', '0011_alter_image_comment_alter_image_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='image_commented_on',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='instagram.image'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='likes',
            name='liked_image',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='instagram.image'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='image',
            name='comment',
        ),
        migrations.AddField(
            model_name='image',
            name='comment',
            field=models.ManyToManyField(related_name='comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='image',
            name='like',
        ),
        migrations.AddField(
            model_name='image',
            name='like',
            field=models.ManyToManyField(related_name='image_likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
