# Generated by Django 4.0.4 on 2022-06-07 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0012_comments_image_commented_on_likes_liked_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='uploaded_by',
            new_name='uploader',
        ),
    ]
