# Generated by Django 4.0.4 on 2022-06-07 12:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('instagram', '0013_rename_uploaded_by_image_uploader'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='uploader',
        ),
        migrations.AddField(
            model_name='image',
            name='uploader_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='uploader', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
