# Generated by Django 4.0.4 on 2022-06-07 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0015_alter_image_uploader_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='uploader_id',
            new_name='uploaded_by',
        ),
    ]
