# Generated by Django 4.0.4 on 2022-06-07 12:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('instagram', '0018_alter_image_uploaded_by'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ('-date_uploaded',), 'verbose_name_plural': 'images'},
        ),
        migrations.AlterField(
            model_name='image',
            name='comment',
            field=models.ManyToManyField(null=True, related_name='comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='image',
            name='like',
            field=models.ManyToManyField(null=True, related_name='image_likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
