# Generated by Django 4.0.4 on 2022-06-07 18:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0020_alter_comments_image_commented_on'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='image',
            name='like',
        ),
        migrations.AddField(
            model_name='image',
            name='comments',
            field=models.ManyToManyField(null=True, related_name='comments', to='instagram.comments'),
        ),
        migrations.AddField(
            model_name='image',
            name='likes',
            field=models.ManyToManyField(null=True, related_name='image_likes', to='instagram.likes'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='image_commented_on',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_comments', to='instagram.image'),
        ),
        migrations.AlterField(
            model_name='likes',
            name='liked_image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_likes', to='instagram.image'),
        ),
    ]
