# Generated by Django 4.0.4 on 2022-06-07 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0021_remove_image_comment_remove_image_like_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='comments',
            field=models.ManyToManyField(related_name='comments', to='instagram.comments'),
        ),
        migrations.AlterField(
            model_name='image',
            name='likes',
            field=models.ManyToManyField(related_name='image_likes', to='instagram.likes'),
        ),
    ]
