# Generated by Django 4.0.4 on 2022-06-07 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0023_remove_image_likes_image_likes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comments',
            options={'ordering': ('comment_date',), 'verbose_name_plural': 'comments'},
        ),
    ]
