# Generated by Django 4.0.4 on 2022-06-08 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0024_alter_comments_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='likes',
            field=models.IntegerField(null=True, verbose_name='Likes'),
        ),
    ]
